parameters:
    database_host: '%env(CLEARDB_DATABASE_URL)%'
    database_port: ~
    database_name: products
    database_user: '%env(DB_USER)%'
    database_password: '%env(DB_PASS)%'
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~